log stderr all;
router id 192.0.2.1;

protocol device {
}

protocol static test_routes {
    ipv6;
    route fd00:99::/64 blackhole;
}

protocol babel ranet {
    ipv6 {
        import all;
        export where source = RTS_STATIC;
    };
    randomize router id;
    interface "swan0" {
        type tunnel;
        rxcost 32;
        hello interval 500 ms;
        update interval 1 s;
        rtt cost 1024;
        rtt max 1024 ms;
        rx buffer 1500;
    };
}
