charon-systemd {
    # ranet uses one explicit UDP-encapsulated port for both IKE and ESP.
    port = 0
    port_nat_t = 13000
    load_modular = yes

    plugins {
        include strongswan.d/charon/*.conf
    }

    filelog {
        stderr {
            default = 1
            ike = 2
            cfg = 1
            flush_line = yes
        }
    }
}

include strongswan.d/*.conf
